// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
