// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UID holds the value of the "uid" field.
	UID uint32 `json:"uid,omitempty"`
	// Lable holds the value of the "lable" field.
	Lable string `json:"lable,omitempty"`
	// Complete holds the value of the "complete" field.
	Complete bool `json:"complete,omitempty"`
}

// FromRows scans the sql response data into Task.
func (t *Task) FromRows(rows *sql.Rows) error {
	var vt struct {
		ID       int
		UID      sql.NullInt64
		Lable    sql.NullString
		Complete sql.NullBool
	}
	// the order here should be the same as in the `task.Columns`.
	if err := rows.Scan(
		&vt.ID,
		&vt.UID,
		&vt.Lable,
		&vt.Complete,
	); err != nil {
		return err
	}
	t.ID = vt.ID
	t.UID = uint32(vt.UID.Int64)
	t.Lable = vt.Lable.String
	t.Complete = vt.Complete.Bool
	return nil
}

// Update returns a builder for updating this Task.
// Note that, you need to call Task.Unwrap() before calling this method, if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Task) Update() *TaskUpdateOne {
	return (&TaskClient{t.config}).UpdateOne(t)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (t *Task) Unwrap() *Task {
	tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	t.config.driver = tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v", t.ID))
	builder.WriteString(", uid=")
	builder.WriteString(fmt.Sprintf("%v", t.UID))
	builder.WriteString(", lable=")
	builder.WriteString(t.Lable)
	builder.WriteString(", complete=")
	builder.WriteString(fmt.Sprintf("%v", t.Complete))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task

// FromRows scans the sql response data into Tasks.
func (t *Tasks) FromRows(rows *sql.Rows) error {
	for rows.Next() {
		vt := &Task{}
		if err := vt.FromRows(rows); err != nil {
			return err
		}
		*t = append(*t, vt)
	}
	return nil
}

func (t Tasks) config(cfg config) {
	for _i := range t {
		t[_i].config = cfg
	}
}
