// Code generated by entc, DO NOT EDIT.

package ent

import (
	"backend/ent/task"
	"context"
	"errors"

	"github.com/facebookincubator/ent/dialect/sql"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	lable      *string
	isComplete *bool
}

// SetLable sets the lable field.
func (tc *TaskCreate) SetLable(s string) *TaskCreate {
	tc.lable = &s
	return tc
}

// SetIsComplete sets the isComplete field.
func (tc *TaskCreate) SetIsComplete(b bool) *TaskCreate {
	tc.isComplete = &b
	return tc
}

// Save creates the Task in the database.
func (tc *TaskCreate) Save(ctx context.Context) (*Task, error) {
	if tc.lable == nil {
		return nil, errors.New("ent: missing required field \"lable\"")
	}
	if tc.isComplete == nil {
		return nil, errors.New("ent: missing required field \"isComplete\"")
	}
	return tc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tc *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	var (
		builder = sql.Dialect(tc.driver.Dialect())
		t       = &Task{config: tc.config}
	)
	tx, err := tc.driver.Tx(ctx)
	if err != nil {
		return nil, err
	}
	insert := builder.Insert(task.Table).Default()
	if value := tc.lable; value != nil {
		insert.Set(task.FieldLable, *value)
		t.Lable = *value
	}
	if value := tc.isComplete; value != nil {
		insert.Set(task.FieldIsComplete, *value)
		t.IsComplete = *value
	}
	id, err := insertLastID(ctx, tx, insert.Returning(task.FieldID))
	if err != nil {
		return nil, rollback(tx, err)
	}
	t.ID = int(id)
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return t, nil
}
