// Code generated by entc, DO NOT EDIT.

package task

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLable holds the string denoting the lable vertex property in the database.
	FieldLable = "lable"
	// FieldIsComplete holds the string denoting the iscomplete vertex property in the database.
	FieldIsComplete = "is_complete"

	// Table holds the table name of the task in the database.
	Table = "tasks"
)

// Columns holds all SQL columns are task fields.
var Columns = []string{
	FieldID,
	FieldLable,
	FieldIsComplete,
}
