/*
 * API TODO list
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Contact: winpooh32@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todo

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ListGet - Gets all TODO tasks.
func ListGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// TaskDelete - Deletes task by id.
func TaskDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// TaskPut - Adds or update TODO task.
func TaskPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
