/*
 * API TODO list
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Contact: winpooh32@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todo

// Task - Task item body.
type Task struct {
	Id *int32 `json:"id"`

	Lable *string `json:"lable"`

	IsComplete *bool `json:"isComplete"`
}
