/*
 * API TODO list
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Contact: winpooh32@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todo

// Error - Error response body.
type Error struct {
	Code string `json:"code"`

	Message string `json:"message"`
}
