/*
 * API TODO list
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Contact: winpooh32@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todo

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter(router *gin.Engine) *gin.Engine {
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

var routes = Routes{
	{
		"ListGet",
		http.MethodGet,
		"/v1/list",
		ListGet,
	},

	{
		"TaskDelete",
		http.MethodDelete,
		"/v1/task",
		TaskDelete,
	},

	{
		"TaskPut",
		http.MethodPut,
		"/v1/task",
		TaskPut,
	},
}
